Add bookings
aDukeFan/java-shareit pull request #2
Opened 2024-06-13 14:35 UTC by aDukeFan

2024-06-16 16:22 UTC, afomkina requested changes

2024-06-16 16:22 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2024-06-16 16:22 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

2024-06-16 16:22 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +import javax.persistence.*;
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-06-16 16:22 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2024-06-16 16:22 UTC, afomkina commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +//@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Нужно поправить тест, чтобы он работал, а не комментировать его

2024-06-17 06:09 UTC, aDukeFan commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +import javax.persistence.*;
Да, ты мне столько раз об этом писала! Всё, теперь дурная привычка окончательно повержена, додумался все-таки зайти в ![Screenshot from 2024-06-17 10-05-57](https://github.com/aDukeFan/java-shareit/assets/148979016/9f4f52b4-64c4-4974-b480-f1a0b25a892b) и поменять настройки =)))

2024-06-18 07:59 UTC, aDukeFan commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +//@TestInstance(TestInstance.Lifecycle.PER_CLASS)
У нас по ТЗ тестирования не было, в 15 спринте ожидается подробное изучение этой темы, поэтому я пока удалил этот тест совсем, а в 15-ом напишу нормальный =)

2024-06-21 13:37 UTC, aDukeFan commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
поправил

2024-06-21 23:28 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +import javax.persistence.*;
Обожаю этот комментарий :)
Молодец, что поправил настройки 💪
FYI я себе ставлю 99 и 99, чтобы точно не было *

2024-06-21 23:33 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Вышло отлично, молодец

2024-06-21 23:34 UTC, afomkina approved these changes

2024-06-22 08:07 UTC, merged